import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        <header className="py-5 px-4 border border-[#1F2933] shadow-sm">
          <NavBar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
